name: Build and test the project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install Ubuntu dependencies
      run: sudo apt install libboost-python-dev python-is-python3 python3-pip

    - name: install PyPI dependencies
      run: pip install -U pip && pip install -U cmake

    - name: configure the project
      run: cmake -B build -S .

    - name: build the project
      run: cmake --build build

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: build

  test:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - uses: actions/checkout@v3

    - name: install Ubuntu dependencies
      run: sudo apt install libboost-python-dev python-is-python3 python3-pip

    - name: install PyPI dependencies
      run: pip install -U pip && pip install -U cmake

    - uses: actions/download-artifact@v3
      with:
        name: build
        path: build

    - run: ls build
    - run: ls build/tests
    - run: ls build/conception_orientee_objet

    - name: test the project
      run: cmake --build build -t test
      env:
        CTEST_OUTPUT_ON_FAILURE: "ON"
