name: Build and test the project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install PyPI dependencies
      run: pip install -U pip && pip install -U cmake pybind11[global]

    - name: configure the project
      run: cmake -B build -S .

    - name: build the project
      run: cmake --build build

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: build

  test:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install PyPI dependencies
      run: pip install -U pip && pip install -U cmake pybind11[global]

    - uses: actions/download-artifact@v3
      with:
        name: build
        path: build

    - name: build the project
      run: cmake --build build

    - name: test the project
      run: cmake --build build -t test
      env:
        CTEST_OUTPUT_ON_FAILURE: "ON"
